### ISSUE TITLE
Crash upon activation when installed on Fedora

### ISSUE THREAD

**Issue by dominicbarnes** [codebrainz/geany-zencoding#7]
I was able to install `geany-zencoding` from source on my new Fedora-based box. (I've installed quite easily before on Ubuntu, but new to Fedora)

After installation, I get the following error message (revealed from `geany -v`)

```
ImportError: No module named zencoding
Segmentation fault
```

When run via gdb, I got the following backtrace from the time of the segfault:

```
ImportError: No module named zencoding

Program received signal SIGSEGV, Segmentation fault.
0xa6f16b64 in zen_controller_set_active_profile (zen=0x0, profile=profile@entry=0xa6f181d6 "xhtml") at zen-controller.c:238
238             result = PyObject_CallObject(zen->set_active_profile, args);
(gdb) bt
#0  0xa6f16b64 in zen_controller_set_active_profile (zen=0x0, profile=profile@entry=0xa6f181d6 "xhtml") at zen-controller.c:238
#1  0xa6f1652a in plugin_init (data=<optimized out>) at plugin.c:519
#2  0x080c3d03 in plugin_new ()
#3  0x080c5325 in pm_plugin_toggled ()
#4  0x42a24152 in g_cclosure_marshal_VOID__STRINGv () from /lib/libgobject-2.0.so.0
#5  0x42a21a26 in _g_closure_invoke_va () from /lib/libgobject-2.0.so.0
#6  0x42a3ba83 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#7  0x42a3c654 in g_signal_emit () from /lib/libgobject-2.0.so.0
#8  0x469c6460 in gtk_cell_renderer_toggle_activate () from /lib/libgtk-x11-2.0.so.0
#9  0x469bbbe2 in gtk_cell_renderer_activate () from /lib/libgtk-x11-2.0.so.0
#10 0x46bc2d49 in gtk_tree_view_column_cell_process_action.isra.8 () from /lib/libgtk-x11-2.0.so.0
#11 0x46bc2fc0 in _gtk_tree_view_column_cell_event () from /lib/libgtk-x11-2.0.so.0
#12 0x46bb5c60 in gtk_tree_view_button_press () from /lib/libgtk-x11-2.0.so.0
#13 0x46a8198e in _gtk_marshal_BOOLEAN__BOXED () from /lib/libgtk-x11-2.0.so.0
#14 0x42a20275 in g_type_class_meta_marshal () from /lib/libgobject-2.0.so.0
#15 0x42a217de in g_closure_invoke () from /lib/libgobject-2.0.so.0
#16 0x42a341ca in signal_emit_unlocked_R () from /lib/libgobject-2.0.so.0
#17 0x42a3c0ab in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#18 0x42a3c654 in g_signal_emit () from /lib/libgobject-2.0.so.0
#19 0x46bd3683 in gtk_widget_event_internal () from /lib/libgtk-x11-2.0.so.0
#20 0x46a7f654 in gtk_propagate_event () from /lib/libgtk-x11-2.0.so.0
#21 0x46a7fa90 in gtk_main_do_event () from /lib/libgtk-x11-2.0.so.0
#22 0x468d25a9 in gdk_event_dispatch () from /lib/libgdk-x11-2.0.so.0
#23 0x428fa556 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#24 0x428fa920 in g_main_context_iterate.isra.23 () from /lib/libglib-2.0.so.0
#25 0x428fadc3 in g_main_loop_run () from /lib/libglib-2.0.so.0
#26 0x46a7e700 in gtk_main () from /lib/libgtk-x11-2.0.so.0
#27 0x080853d4 in main ()
```

Unfortunately, I'm not either a C or Python developer, so I'm at a loss when it comes to further debugging.

**Comment by jEsuSdA** [comment]
I suffer same issue in Debian Testing.

Segfault when try to activate. :_(
